import express from "express";
import { PrismaClient } from "@prisma/client";
import { createNotification } from "../../notifications/notificationRoute.js";

const prisma = new PrismaClient();
const generateBillingRouter = express.Router();

/* EMPLOYEE → GENERATE BILL */
generateBillingRouter.post("/generate", async (req, res) => {
  try {
    const { clientId, description, amount, dueDate, generatedBy,items } = req.body;

    if (!clientId || !amount || !dueDate|| !generatedBy) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const bill = await prisma.bills.create({
      data: {
        clientId,
        description,
        amount,
        dueDate,
        generatedBy: generatedBy,
        status: "PENDING",
        items: items || null,
      },
    });

     await createNotification({
      title: "Bill Generated",
      message: "Bill has been generated",
      type: "SUCCESS",
    });


    res.status(201).json(bill);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to generate bill" });
  }
});


/* GET bills generated by current user */
generateBillingRouter.get("/list", async (req, res) => {
  const userId = req.query.userId;

  if (!userId) {
    return res.status(400).json({ error: "userId is required" });
  }

  try {
    const bills = await prisma.bills.findMany({
      where: { generatedBy: userId.toString() },
    });
    res.json(bills);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Failed to fetch bills" });
  }
});

export default generateBillingRouter;
